Repository IIITM-Jay/Property-management-System-Django-Full-Stack-, pull requests merged in 2020-12, with the labels that each got.

#3 An enhancement related to adding actions related to admin
  admin/admin_actions.py
Labels: enhancement

#4 Added Approval Section
  admin/admin_approval.py
Labels: enhancement

#5 Revert "An enhancement related to adding actions related to admin"
  admin/admin_actions.py
Labels: revert

#6 Update settings.py
  backend management/settings.py
Labels: duplicate
