Repository IIITM-Jay/Property-management-System-Django-Full-Stack-, pull requests merged in 2021-01, with the labels that each got.

#19 Added password_change file
  admin/password.html
Labels: HTML, enhancement, front-end, mid-level, static files

#21 Image path is not correctly embedded
  DBMS module/System_requirement_analysis.md
  DBMS module/flow_sequence_diag.md
Labels: Broken Links, beginner-level, bug

#30 Add Contributors Table in README.md
  README.md
Labels: DWoC, Level-4, avg-complexity, deployment, documentation, enhancement
