Repository IIITM-Jay/Property-management-System-Django-Full-Stack-, pull requests merged in 2021-02, with the labels that each got.

#24 Changed Image positions and dimensions and added border to image
  DBMS module/flow_sequence_diag.md
Labels: HTML, css, enhancement, good first issue, static files

#18 Added approval 2.O version
  admin/approval2.html
Labels: HTML, css, deployment, enhancement, front-end, javascript, mid-level

#35 Updated readme.md #14
  README.md
Labels: DWoC, Level 1, beginner-level

#38 Update README.md
  README.md
Labels: DWoC, Level 1
